url: "http://simplifyingideas.com.br"
logo: "/assets/images/dtm.png"
title: "Simplifying Ideas"
email: email@dtmtec.com.br
cover: "/assets/images/cover.jpg"

markdown: redcarpet
highlighter: pygments

paginate:	50

social:
  - icon:	twitter
    url:	https://twitter.com/DTMtec
    share_url: http://twitter.com/share

  - icon:	github
    url:	https://github.com/DTMtec

  - icon:	facebook
    url:	https://facebook.com/DTMtec

authors:
  luis.vasconcellos:
    name: Luis Vasconcellos
    github: http://github.com/vasconcelloslf
    twitter: http://twitter.com/vasconcelloslf
    linkedin: https://www.linkedin.com/profile/view?id=108062830
    signature: developer. vim and tmux enthusiast.
    description: |
      Sou apaixonado por desenvolvimento e procuro escrever sempre sobre assuntos relacionados a plataforma web, cordova, rails, javascript e seus respectivos frameworks.
    display_signature: true
  marcelo.murad:
    name: Marcelo Murad
    twitter: http://twitter.com/marcelo_murad
  rafael.mahler:
    name: Rafael Mahler
    signature: UI / UX Designer at DTM Tecnologia da Informação
    description: |
      Meu principal foco de atuação é a criação de projetos com interfaces intuitivas, fáceis e agradáveis de utilizar. Transito bem entre publicidade, marketing e entretenimento, pesquisando continuamente e filtrando tendências para aplicação no dia a dia dos nossos clientes.
    twitter: http://twitter.com/rafamahler
    github: http://github.com/rafaelmahler
    linkedin: https://br.linkedin.com/pub/rafael-mahler/15/444/a82
    display_signature: true
  otavio.cardoso:
    name: Otavio Cardoso
    twitter: http://twitter.com/realotaviko
  felipe.mesquita:
    name: Felipe Mesquita
    twitter: http://twitter.com/fmesquitacunha
  gustavo.kloh:
    name: Gustavo Kloh
    twitter: http://twitter.com/gustavokloh
  vicente.mundim:
    name: Vicente Mundim
    twitter: http://twitter.com/vicente.mundim
  joao.mello:
    name: João Mello
    twitter: http://twitter.com/jhonny_carreira
  julian.gutierrez:
    name: Julian Gutierrez
    twitter: http://twitter.com/vasconcelloslf
  carlos.figueiredo:
    name: Carlos Figueiredo
    twitter: http://twitter.com/cefigueiredo
  tomas.lima:
    name: Tomas Lima
    twitter: http://twitter.com/vasconcelloslf
  valeria.parajara:
    name: Valéria Parajara
    twitter: http://twitter.com/valparajara
