markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

title: "Simplifying Ideas"
description: >
  DTM

email: email@dtmtec.com.br
logo: "/assets/images/dtm.png"
cover: "/assets/images/cover.jpg"

paginate:	5

name: 'DTM'
author: 'DTM'
author_image: "/assets/images/luis.jpg"

url: "http://blog.dtmtec.com.br"
baseurl: ""

social:
  - icon:	twitter
    url:	https://twitter.com/DTMtec
    desc: Follow me
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/DTMtec
    desc:	Fork me

  - icon:	facebook
    url:	https://facebook.com/DTMtec
    desc:	Fork me

authors:
  luis.vasconcellos:
    name: Luis Vasconcellos
    signature: developer. vim and tmux enthusiast.
    description: Gosto de postar sobre tal, tal, tal e tal.
