markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

title: "Simplifying Ideas"

email: email@dtmtec.com.br
logo: "/assets/images/dtm.png"
cover: "/assets/images/cover.jpg"

paginate:	50

name: 'DTM'
author: 'DTM'
author_image: "/assets/images/luis.jpg"

url: "http://blog.dtmtec.com.br"
baseurl: ""

social:
  - icon:	twitter
    url:	https://twitter.com/DTMtec
    desc: Follow me
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/DTMtec
    desc:	Fork me

  - icon:	facebook
    url:	https://facebook.com/DTMtec
    desc:	Fork me

authors:
  luis.vasconcellos:
    name: Luis Vasconcellos
    twitter: http://twitter.com/vasconcelloslf
    signature: developer. vim and tmux enthusiast.
    description: |
      Sou apaixonado por desenvolvimento e procuro escrever sempre sobre assuntos relacionados a plataforma web, cordova, rails, javascript e seus respectivos frameworks.
    display_signature: true
  marcelo.murad:
    name: Marcelo Murad
    twitter: http://twitter.com/marcelo_murad
  rafael.mahler:
    name: Rafael Mahler
    twitter: http://twitter.com/rafamahler
  otavio.cardoso:
    name: Otavio Cardoso
    twitter: http://twitter.com/realotaviko
  felipe.mesquita:
    name: Felipe Mesquita
    twitter: http://twitter.com/fmesquitacunha
  gustavo.kloh:
    name: Gustavo Kloh
    twitter: http://twitter.com/gustavokloh
  vicente.mundim:
    name: Vicente Mundim
    twitter: http://twitter.com/vicente.mundim
  joao.mello:
    name: João Mello
    twitter: http://twitter.com/jhonny_carreira
  julian.gutierrez:
    name: Julian Gutierrez
    twitter: http://twitter.com/vasconcelloslf
  carlos.figueiredo:
    name: Carlos Figueiredo
    twitter: http://twitter.com/cefigueiredo
  tomas.lima:
    name: Tomas Lima
    twitter: http://twitter.com/vasconcelloslf
  valeria.parajara:
    name: Valéria Parajara
    twitter: http://twitter.com/valparajara
